Repository KB-project-14/DanJi-BE, pull requests merged in 2025-08, with the labels that each got.

#85 [fix] : 가맹점 저장 로직 수정
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantServiceImpl.java
  src/main/java/org/danji/localCurrency/domain/LocalCurrencyVO.java
  src/main/java/org/danji/localCurrency/mapper/LocalCurrencyMapper.java
  src/main/resources/db/migration/V0.0.17__AlterModifyRegion.sql
  src/main/resources/db/migration/V0.0.18__InsertLocalCurrency.sql
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: fix

#92 [fix]: 스케줄 매 자정으로 변경
  src/main/java/org/danji/batch/scheduler/AvailableMerchantJobScheduler.java
Labels: fix

#96 [fix] : wallet 응답 객체 수정
  src/main/java/org/danji/wallet/controller/WalletController.java
  src/main/java/org/danji/wallet/dto/WalletDetailDTO.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
  src/main/java/org/danji/wallet/service/WalletService.java
  src/main/java/org/danji/wallet/service/WalletServiceImpl.java
  src/main/resources/org/danji/wallet/mapper/WalletMapper.xml
Labels: fix

#103 [refactor] : swagger 문서 정리 및 불필요한 도메인 제거
  src/main/java/org/danji/board/controller/BoardController.java
  src/main/java/org/danji/board/domain/BoardAttachmentVO.java
  src/main/java/org/danji/board/domain/BoardVO.java
  src/main/java/org/danji/board/dto/BoardDTO.java
  src/main/java/org/danji/board/mapper/BoardMapper.java
  src/main/java/org/danji/board/service/BoardService.java
  src/main/java/org/danji/board/service/BoardServiceImpl.java
  src/main/java/org/danji/global/config/SwaggerConfig.java
  src/main/java/org/danji/travel/controller/TravelController.java
  src/main/java/org/danji/travel/domain/TravelImageVO.java
  src/main/java/org/danji/travel/domain/TravelVO.java
  src/main/java/org/danji/travel/dto/TravelDTO.java
  src/main/java/org/danji/travel/dto/TravelImageDTO.java
  src/main/java/org/danji/travel/mapper/TravelMapper.java
  src/main/java/org/danji/travel/service/TravelService.java
  src/main/java/org/danji/travel/service/TravelServiceImpl.java
Labels: refactor

#104 [refactor] : flyway에 불필요한 테이블 제거 쿼리 추가
  src/main/resources/db/migration/V0.0.20__DropBoardTable.sql
Labels: refactor

#111 [feat] : 이미지 파일 저장 후 wallet 조회 추가
  src/main/java/org/danji/global/config/ServletConfig.java
  src/main/resources/db/migration/V0.0.24__InsertFilesTable.sql
  src/main/resources/org/danji/wallet/mapper/WalletMapper.xml
  src/main/resources/static/images/busan.jpg
  src/main/resources/static/images/daegu.jpg
  src/main/resources/static/images/gunsan.jpg
  src/main/resources/static/images/gwangju.jpg
  src/main/resources/static/images/iksan.jpg
  src/main/resources/static/images/jeju.jpg
  src/main/resources/static/images/ulsan.jpg
Labels: feat

#114 [refactor] : 쿼리 로그 확인을 위한 log4j2.xml 설정 추가
  src/main/java/org/danji/batch/scheduler/AvailableMerchantJobScheduler.java
  src/main/resources/log4j2.xml
Labels: refactor

#118 [fix] : localCurrency 상세 조회 수정
  src/main/java/org/danji/localCurrency/controller/LocalCurrencyController.java
  src/main/java/org/danji/localCurrency/dto/LocalCurrencyDetailDTO.java
  src/main/java/org/danji/localCurrency/mapper/LocalCurrencyMapper.java
  src/main/java/org/danji/localCurrency/service/LocalCurrencyService.java
  src/main/java/org/danji/localCurrency/service/LocalCurrencyServiceImpl.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: fix

#121 [fix] : 지역화폐 리스트 조회 수정
  src/main/java/org/danji/batch/config/AvailableMerchantChunkJobConfig.java
  src/main/java/org/danji/batch/scheduler/AvailableMerchantJobScheduler.java
  src/main/java/org/danji/batch/step/AvailableMerchantProcessor.java
  src/main/java/org/danji/batch/step/LocalCurrencyPartitionedReader.java
  src/main/java/org/danji/localCurrency/domain/LocalCurrencyVO.java
  src/main/java/org/danji/localCurrency/dto/LocalCurrencyDTO.java
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: fix

#123 [fix] : 에러 수정
  src/main/java/org/danji/batch/scheduler/AvailableMerchantJobScheduler.java
  src/main/java/org/danji/localCurrency/mapper/LocalCurrencyMapper.java
  src/main/java/org/danji/localCurrency/service/LocalCurrencyServiceImpl.java
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: fix

#125 [refactor] : Batch 처리 리팩토링
  src/main/java/org/danji/availableMerchant/mapper/AvailableMerchantMapper.java
  src/main/java/org/danji/batch/config/AvailableMerchantChunkJobConfig.java
  src/main/java/org/danji/batch/step/AvailableMerchantProcessor.java
  src/main/java/org/danji/batch/step/AvailableMerchantWriter.java
  src/main/java/org/danji/batch/step/LocalCurrencyPartitionedReader.java
  src/main/java/org/danji/batch/step/LocalCurrencyPartitioner.java
  src/main/java/org/danji/localCurrency/mapper/LocalCurrencyMapper.java
  src/main/resources/org/danji/availableMerchant/mapper/AvailableMerchantMapper.xml
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: refactor

#129 [feat] : 결제 시, 뱃지 추가 로직 구현
  src/main/java/org/danji/memberBadge/mapper/MemberBadgeMapper.java
  src/main/java/org/danji/memberBadge/service/MemberBadgeService.java
  src/main/java/org/danji/memberBadge/service/MemberBadgeServiceImpl.java
  src/main/java/org/danji/transaction/strategy/LocalMixedStrategy.java
  src/main/java/org/danji/transaction/strategy/LocalStrategy.java
  src/main/java/org/danji/wallet/domain/WalletVO.java
  src/main/resources/org/danji/memberBadge/mapper/MemberBadgeMapper.xml
Labels: feat

#140 [Fix] : 지역화폐 조회 수정
  src/main/java/org/danji/batch/step/AvailableMerchantProcessor.java
  src/main/java/org/danji/batch/step/LocalCurrencyPartitioner.java
  src/main/java/org/danji/localCurrency/dto/LocalCurrencyDTO.java
  src/main/resources/db/migration/V0.0.32__UpdateFilesTable_Dokdo.sql
  src/main/resources/db/migration/V0.0.33__UpdateLocalCurrencyTbl.sql
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
  src/main/resources/static/images/badge/dokdospecial.webp
  src/main/resources/static/images/badge/gangwon1.webp
  src/main/resources/static/images/badge/gangwon2.webp
  src/main/resources/static/images/badge/gangwon3.webp
Labels: fix

#144 [chore] : cors 설정 변경
  src/main/java/org/danji/security/config/SecurityConfig.java
Labels: chore

#151 [fix] : 결제 로직 오류 해결
  src/main/java/org/danji/transaction/controller/TransactionController.java
  src/main/java/org/danji/transaction/processor/PaymentProcessor.java
  src/main/java/org/danji/transaction/strategy/LocalStrategy.java
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: fix

#153 [fix] : incentive 아닐때도 충전되도록 로직 수정
  database.sql
  server.webp
  src/main/java/org/danji/security/config/SecurityConfig.java
  src/main/java/org/danji/transaction/processor/RechargeProcessor.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
Labels: fix

#156 [fix] : 환불 로직 변경
  src/main/java/org/danji/transaction/processor/RefundProcessor.java
Labels: fix
