Repository KB-project-14/DanJi-BE, pull requests merged in 2025-07, with the labels that each got.

#18 [chore] : 지역화폐 가맹점 패키지 세팅(VO 설정)
  src/main/java/org/danji/availableMerchant/controller/AvailableMerchantController.java
  src/main/java/org/danji/availableMerchant/domain/AvailableMerchantVO.java
  src/main/java/org/danji/availableMerchant/dto/AvailableMerchantDTO.java
  src/main/java/org/danji/availableMerchant/mapper/AvailableMerchantMapper.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantService.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantServiceImpl.java
Labels: chore

#36 feat: 가맹점 추가 API 개발(uuid 해결 안됨)
  src/main/java/org/danji/availableMerchant/controller/AvailableMerchantController.java
  src/main/java/org/danji/availableMerchant/domain/AvailableMerchantVO.java
  src/main/java/org/danji/availableMerchant/dto/AvailableMerchantDTO.java
  src/main/java/org/danji/availableMerchant/mapper/AvailableMerchantMapper.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantService.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantServiceImpl.java
  src/main/java/org/danji/global/config/RootConfig.java
  src/main/java/org/danji/global/config/ServletConfig.java
  src/main/resources/org/danji/availableMerchant/mapper/AvailableMerchantMapper.xml
Labels: feat

#38 chore: 플라이웨이 추가
  src/main/resources/db/migration/V0.0.3__insert_korean_region.sql
Labels: chore

#39 style: 최종 변경!
  src/main/resources/db/migration/V0.0.3__insert_korean_region.sql
Labels: fix

#41 [refactor] : 지역화폐 충전 기능 리팩토링
  .idea/dataSources.xml
  src/main/java/org/danji/cashback/converter/CashbackConverter.java
  src/main/java/org/danji/cashback/domain/CashbackVO.java
  src/main/java/org/danji/transaction/converter/TransactionConverter.java
  src/main/java/org/danji/transaction/domain/TransactionVO.java
  src/main/java/org/danji/transaction/dto/response/TransactionDTO.java
  src/main/java/org/danji/transaction/service/TransactionServiceImpl.java
  src/main/resources/db/migration/V0.0.4__AddColumn_transaction.sql
  src/main/resources/db/migration/V0.0.5__AddColumn_wallet.sql
  src/main/resources/org/danji/cashback/mapper/CashBackMapper.xml
  src/main/resources/org/danji/transaction/mapper/TransactionMapper.xml
Labels: refactor

#43 [feat]: 지역 리스트 조회 기능
  .idea/.gitignore
  .idea/.name
  .idea/codeStyles/codeStyleConfig.xml
  .idea/description.html
  .idea/mybatisx/templates.xml
  .idea/project-template.xml
  .idea/sqldialects.xml
  .idea/template-meta.xml
  src/main/java/org/danji/availableMerchant/domain/AvailableMerchantVO.java
  src/main/java/org/danji/global/config/RootConfig.java
  src/main/java/org/danji/global/config/ServletConfig.java
  src/main/java/org/danji/region/controller/RegionController.java
  src/main/java/org/danji/region/domain/RegionVO.java
  src/main/java/org/danji/region/dto/RegionDTO.java
  src/main/java/org/danji/region/mapper/RegionMapper.java
  src/main/java/org/danji/region/service/RegionService.java
  src/main/java/org/danji/region/service/RegionServiceImpl.java
  src/main/resources/org/danji/region/mapper/RegionMapper.xml
Labels: feat

#49 [feat] : 지역화폐 환불 기능 구현
  src/main/java/org/danji/cashback/mapper/CashbackMapper.java
  src/main/java/org/danji/global/config/RootConfig.java
  src/main/java/org/danji/transaction/controller/TransactionController.java
  src/main/java/org/danji/transaction/dto/request/TransferDTO.java
  src/main/java/org/danji/transaction/enums/TransferType.java
  src/main/java/org/danji/transaction/processor/RechargeProcessor.java
  src/main/java/org/danji/transaction/processor/RefundProcessor.java
  src/main/java/org/danji/transaction/processor/TransferProcessor.java
  src/main/java/org/danji/transaction/service/TransactionService.java
  src/main/java/org/danji/transaction/service/TransactionServiceImpl.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
  src/main/resources/db/migration/V0.0.3__Insert_Korean_Region.sql
  src/main/resources/db/migration/V0.0.4__AddColumn_Transaction.sql
  src/main/resources/db/migration/V0.0.5__AddColumn_Wallet.sql
  src/main/resources/db/migration/V0.0.6__AddCashbackTable.sql
  src/main/resources/org/danji/cashback/mapper/CashBackMapper.xml
Labels: feat

#52 [feat] : 지역화폐 가맹점 리스트 조회 구현(공공데이터 가져오기 실패)
  .idea/dataSources.xml
  database.sql
  src/main/java/org/danji/availableMerchant/controller/AvailableMerchantController.java
  src/main/java/org/danji/availableMerchant/domain/AvailableMerchantVO.java
  src/main/java/org/danji/availableMerchant/dto/AvailableMerchantDTO.java
  src/main/java/org/danji/availableMerchant/dto/MerchantFilterDTO.java
  src/main/java/org/danji/availableMerchant/mapper/AvailableMerchantMapper.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantService.java
  src/main/java/org/danji/availableMerchant/service/AvailableMerchantServiceImpl.java
  src/main/java/org/danji/availableMerchant/util/AvailableMerchantInitializer.java
  src/main/java/org/danji/localCurrency/mapper/LocalCurrencyMapper.java
  src/main/java/org/danji/transaction/controller/TransactionController.java
  src/main/resources/org/danji/availableMerchant/mapper/AvailableMerchantMapper.xml
  src/main/resources/org/danji/localCurrency/mapper/LocalCurrencyMapper.xml
Labels: feat

#63 [feat] : 지역화폐 끼리 환전 기능 구현
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/org/danji/transaction/controller/TransactionController.java
  src/main/java/org/danji/transaction/converter/TransactionConverter.java
  src/main/java/org/danji/transaction/dto/request/TransferDTO.java
  src/main/java/org/danji/transaction/enums/TransferType.java
  src/main/java/org/danji/transaction/processor/ConvertProcessor.java
  src/main/java/org/danji/transaction/processor/RechargeProcessor.java
  src/main/java/org/danji/transaction/processor/RefundProcessor.java
  src/main/java/org/danji/transaction/service/TransactionService.java
  src/main/java/org/danji/transaction/service/TransactionServiceImpl.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
  src/main/resources/org/danji/wallet/mapper/WalletMapper.xml
Labels: feat

#64 [refactor] : 충전, 환불 로직 리팩토링
  src/main/java/org/danji/global/error/ErrorCode.java
  src/main/java/org/danji/transaction/processor/RechargeProcessor.java
  src/main/java/org/danji/transaction/processor/RefundProcessor.java
  src/main/java/org/danji/transaction/validator/WalletValidator.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
  src/main/resources/org/danji/wallet/mapper/WalletMapper.xml
Labels: refactor

#83 [refactor] : swagger 문서 갱신 및 메소드 재사용
  src/main/java/org/danji/global/error/ErrorResponse.java
  src/main/java/org/danji/transaction/controller/TransactionController.java
  src/main/java/org/danji/transaction/dto/request/PaymentDTO.java
  src/main/java/org/danji/transaction/dto/request/TransactionFilterDTO.java
  src/main/java/org/danji/transaction/dto/request/TransferDTO.java
  src/main/java/org/danji/transaction/enums/Type.java
  src/main/java/org/danji/transaction/processor/PaymentProcessor.java
  src/main/java/org/danji/transaction/processor/RechargeProcessor.java
  src/main/java/org/danji/transaction/processor/RefundProcessor.java
  src/main/java/org/danji/transaction/strategy/LocalMixedStrategy.java
  src/main/java/org/danji/transaction/strategy/LocalStrategy.java
  src/main/java/org/danji/wallet/mapper/WalletMapper.java
  src/main/resources/org/danji/wallet/mapper/WalletMapper.xml
Labels: refactor
